In [26]:
#load necessary modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
#load the dataset
df = pd.read_csv('market.csv')
df.head(5)

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Visualization of Most Frequent Items
plt.figure(figsize=(10, 6))
data[0].value_counts().head(20).plot.bar(color=plt.cm.inferno(np.linspace(0, 1, 20)))
plt.title('Top 20 Most Frequent Items')
plt.ylabel('Counts')
plt.xlabel('Items')
plt.show()

# Tree Map of Most Frequent Items
import squarify
plt.figure(figsize=(10, 10))
items = data[0].value_counts().head(20)
squarify.plot(sizes=items.values, label=items.index, alpha=0.7, color=plt.cm.inferno(np.linspace(0, 1, 20)))
plt.title('Tree Map of Most Frequent Items')
plt.axis('off')
plt.show()

# Prepare data for Apriori algorithm
transactions = [[str(data.values[i, j]) for j in range(20) if str(data.values[i, j]) != 'nan'] for i in range(len(data))]
from mlxtend.preprocessing import TransactionEncoder
transac = TransactionEncoder()
dataset = transac.fit_transform(transactions)
df = pd.DataFrame(dataset, columns=transac.columns_)

# Apriori Algorithm
from mlxtend.frequent_patterns import apriori, association_rules
frequent_itemsets = apriori(df, min_support=0.003, use_colnames=True)
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1)

# Filter rules with high lift and confidence
filtered_rules = rules[(rules['lift'] >= 5) & (rules['confidence'] >= 0.4)]

# Display results
print(filtered_rules.head(10))